// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
String GoogleMapkey="AIzaSyDgyhwP7oP1mo43sLvlyvg25Kq7LLByNNE";

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5WavWH2CRA4RvRHCgP6GkvwYgblZssxo',
    appId: '1:987757075985:web:2e1ec403c7198c20abdbb0',
    messagingSenderId: '987757075985',
    projectId: 'shesos-2765e',
    authDomain: 'shesos-2765e.firebaseapp.com',
    storageBucket: 'shesos-2765e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2uCXAUZA9PX5A9o_HLer6eWlkRTpOKI',
    appId: '1:987757075985:android:dd64de38738f0af0abdbb0',
    messagingSenderId: '987757075985',
    projectId: 'shesos-2765e',
    storageBucket: 'shesos-2765e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZucbiGFxn1BIgQbwXHrIQE-5m_eEJJqA',
    appId: '1:987757075985:ios:f9c86ad7f6637616abdbb0',
    messagingSenderId: '987757075985',
    projectId: 'shesos-2765e',
    storageBucket: 'shesos-2765e.firebasestorage.app',
    iosClientId: '987757075985-8977gmp14k482k5bdptfng36dast4ru1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheSos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZucbiGFxn1BIgQbwXHrIQE-5m_eEJJqA',
    appId: '1:987757075985:ios:f9c86ad7f6637616abdbb0',
    messagingSenderId: '987757075985',
    projectId: 'shesos-2765e',
    storageBucket: 'shesos-2765e.firebasestorage.app',
    iosClientId: '987757075985-8977gmp14k482k5bdptfng36dast4ru1.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheSos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5WavWH2CRA4RvRHCgP6GkvwYgblZssxo',
    appId: '1:987757075985:web:c4442e72f93a1ba5abdbb0',
    messagingSenderId: '987757075985',
    projectId: 'shesos-2765e',
    authDomain: 'shesos-2765e.firebaseapp.com',
    storageBucket: 'shesos-2765e.firebasestorage.app',
  );

}